---
- name: 在目录主机创建yaml目录
  file:
    path: /etc/kansctl/yaml/node-exporter
    state: directory

- name: 渲染node-exporter YAML 模板
  template:
    src: "{{ item }}.j2"
    dest: "/etc/kansctl/yaml/node-exporter/{{ item }}"
    mode: "0660"
  loop:
    - 01-ds-node_export.yml
    - 02-svc-node_export.yml

- name: 部署node-exporter实例
  shell: kubectl apply -f /etc/kansctl/yaml/node-exporter
