#!/bin/bash

######################################################################
#                                                                    #
# AUTHOR:          kubecy                                            #
# SCRIPT ID:       kansctl                                           #
# FUNCTION:        install mysql8 and mysql5.7 on Debian and RedHat  #
# CREATE TIME:     2024/11/30                                        #
# PLATFORM:        Linux                                             #
#                                                                    #
######################################################################
set -o nounset
set -o errexit


function logger() {
  TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
  local FID=$(basename "${BASH_SOURCE[1]}")
  local SOURCE="\033[35m[$FID:${BASH_LINENO[0]}]\033[0m"
  case "$1" in
    debug)
      echo -e "\033[35m$TIMESTAMP\033[0m $SOURCE \033[36mDEBUG $2\033[0m"
      ;;
    info)
      echo -e "\033[35m$TIMESTAMP\033[0m $SOURCE \033[32mINFO $2\033[0m"
      ;;
    warn)
      echo -e "\033[35m$TIMESTAMP\033[0m $SOURCE \033[33mWARN $2\033[0m"
      ;;
    error)
      echo -e "\033[35m$TIMESTAMP\033[0m $SOURCE \033[31mERROR $2\033[0m"
      ;;
    *) ;;
  esac
}



function usage() {
    echo -e "\033[33mUsage:\033[0m kansctl command -e <env> -t <service> [args]"
    cat <<EOF
-------------------------------------------------------------------------------------
kansctl command:
    apply         <service>        应用集群资源配置（执行部署）
    delete        <service>        删除集群资源配置（执行卸载）
    update        <service>        滚动更新指定服务
    rollback      <service>        回滚上一个服务版本
    history       <service>        查看服务版本发布历史
    scale         <service>        修改服务副本数量
    monitor       <service>        监控服务运行状态

kansctl env:
    moone_prod                     moone 生产环境
    moone_dev                      moone 开发环境
    moone_test                     moone 测试环境

kansctl service:
    redis-single                   redis           单实例
    postgresql-single              postgresql      单实例
    mysql-single                   mysql           单实例
    rabbitmq-single                rabbitmq        单实例

kansctl examples:
    kansctl apply -e moone_prod -t redis-single
    kansctl update -e moone_prod -t redis-single --image=redis:6.14.8
    
EOF
}


function main() {

  [ "$#" -gt 0 ] || { usage >&2; exit 2; }

  case "$1" in
      (kca-renew)
          [ "$#" -eq 2 ] || { usage >&2; exit 2; }
          renew-ca "$2"
          ;;
      (help)
          [ "$#" -gt 1 ] || { usage >&2; exit 2; }
          help-info "$2"
          exit 0
          ;;
      (*)
          usage
          exit 0
          ;;
  esac
 }

main "$@"
