# 主节点优化配置
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cluster-primary-configmap
  namespace: prod-db
  labels:
    app.bigquant.ai/component: mysql-cluster
    app.bigquant.ai/mysql-cluster-role: primary
    config-type: high-availability
  annotations:
    app.bigquant.ai/component: mysql-cluster
    app.bigquant.ai/mysql-cluster-role: primary
    config-version: "2023.10-prod"
data:
  my.cnf: |-
    [mysqld]
    # ===== 核心配置 =====
    server-id = 1
    log_bin = /bitnami/mysql/binlog/mysql-bin
    binlog_format = ROW
    binlog_row_image = minimal
    gtid_mode = ON
    enforce_gtid_consistency = ON
    
    # ===== 数据安全 =====
    sync_binlog = 1
    innodb_flush_log_at_trx_commit = 1
    innodb_doublewrite = ON
    transaction-isolation = READ-COMMITTED
    
    # ===== 性能优化 =====
    innodb_buffer_pool_size = 12G
    innodb_log_file_size = 2G
    innodb_log_buffer_size = 256M
    innodb_flush_method = O_DIRECT
    innodb_io_capacity = 20000
    innodb_io_capacity_max = 40000
    innodb_thread_concurrency = 0
    max_connections = 500
    thread_cache_size = 100
    table_open_cache = 2000
    
    # ===== 网络与连接 =====
    bind-address = 0.0.0.0
    max_allowed_packet = 256M
    skip_name_resolve = ON
    connect_timeout = 10
    wait_timeout = 28800
    interactive_timeout = 28800
    
    # ===== 日志与监控 =====
    slow_query_log = ON
    long_query_time = 2
    log_queries_not_using_indexes = ON
    log_slow_admin_statements = ON
    log_slow_slave_statements = ON
    log_error = /opt/bitnami/mysql/logs/mysqld-error.log
    slow_query_log_file = /opt/bitnami/mysql/logs/mysqld-slow.log
    performance_schema = ON
    
    # ===== 路径配置 =====
    basedir = /opt/bitnami/mysql
    datadir = /bitnami/mysql/data
    tmpdir = /opt/bitnami/mysql/tmp
    socket = /opt/bitnami/mysql/tmp/mysql.sock
    pid-file = /opt/bitnami/mysql/tmp/mysqld.pid
    plugin_dir = /opt/bitnami/mysql/lib/plugin
    
    # ===== 字符集配置 =====
    character_set_server = utf8mb4
    collation_server = utf8mb4_unicode_ci
    default_authentication_plugin = mysql_native_password
    
    # ===== 复制优化 =====
    binlog_expire_logs_seconds = 604800  # 7天
    binlog_cache_size = 64M
    max_binlog_size = 1G
    sync_source_info = 1
    
    [client]
    socket = /opt/bitnami/mysql/tmp/mysql.sock
    default-character-set = utf8mb4
    
    [mysqld_safe]
    log-error = /opt/bitnami/mysql/logs/mysqld-error.log
    pid-file = /opt/bitnami/mysql/tmp/mysqld.pid

