##生产环境 

k8s_host: "moone_prod"

docker_repo:
  host: "registry.cn-guangzhou.aliyuncs.com"
  image_project: "kansctl"
  image_name: "redis"
  image_version: "6.2.18"

namespace: "moone"

## 服务镜像
service:

  ## 数据库
  redis: 
    image: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/redis:6.2.18"

  postgresql:
    image: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/postgresql:v17.5-alpine3.22"

  mysql:
    image: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/mysql:v8.0.36"

  mysqld_exporter:
    image: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/mysqld-exporter:v0.17.2"

  elasticsearch:
    image: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/elasticsearch:v7.17.3"


  ## 初始化容器镜像
  kubecy_shell:
    image: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/os-shell:v12-debian-12-r43"

  bitnami-shell:
    image: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/bitnami-shell:v11-debian-11-r118"
 


  ## 监控告警
  prometheus: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/prometheus:v2.53.4"
  grafana: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/grafana:v11.6.1-debian-12-r1"
  alertmanager: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/alertmanager:v0.27.0"
  node_exporter: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/node-exporter:v1.9.1"
  prometheus_config_reloader: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/prometheus-config-reloader:v0.55.1"
  prometheus_webhook_dingtalk: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/prometheus-webhook-dingtalk:v2.1.0"
  kube_state_metrics: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/kube-state-metrics:2.16.0-debian-12-r3"

  ## 消息队列
  rabbitmq:
    image: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/rabbitmq:v3.13.7-debian-12-r2"
  
  ## 分布式协调服务
  zookeeper: 
    image: "{{ docker_repo.host }}/{{ docker_repo.image_project }}/zookeeper:3.8.5-jre-17-r10"
    pv_path: "/mnt/moone"
