---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: moone-mysql-pv-data-0
  namespace: moone #{{ namespace  }}
  labels:
    app/component: mysql
    app/mysql-role: mysql
  annotations:
    app/component: mysql
    app/mysql-role: mysql
    pv.kubernetes.io/provisioned-by: local-volume-provisioner
spec:
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  storageClassName: prod-db-mysql-cluster-primary-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/ssd-volumes/mysql-primary-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["db-node-01"]
  mountOptions:
    - noatime
    - nodiratime
    - nobarrier
