---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-filebeat-daemonset-config
  namespace: logging
  labels:
    app: "logging-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "logging"
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"

    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:logging-elasticsearch-headless:9200}'

