---
- name: 在目标主机创建 /etc/kansctl/yaml/alertmanager 目录
  file:
    path: /etc/kansctl/yaml/alertmanager
    state: directory

- name: 渲染alertmanager YAML 模板
  template:
    src: "{{ item }}"
    dest: "/etc/kansctl/yaml/alertmanager/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: "0660"
  loop:
    - 01-config-alertmanager.yml.j2
    #- 02-tmpl-alertmanager.yml
    - 03-sts-alertmanager.yml.j2
    - 04-svc-alertmanager.yml.j2
    - 05-ingress-alertmanager.yml.j2

- name: 下发 alertmanager 告警模板
  copy:
    src: 02-tmpl-alertmanager.yml
    dest: /etc/kansctl/yaml/alertmanager/02-tmpl-alertmanager.yml

- name: 部署alertmanager实例
  shell: kubectl apply -f /etc/kansctl/yaml/alertmanager
