---
- name: 安装 alertmanager 服务
  include_tasks: install.yml
  when: state | default('present') == 'present'

- name: 卸载 alertmanager 服务
  include_tasks: delete.yml
  when: state | default('present') == 'absent'
