---
# Source: filebeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-test-filebeat
  namespace: logging
  annotations:
  labels:
    app: "filebeat-test-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "filebeat-test"
---
# Source: filebeat/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-test-filebeat-daemonset-config
  namespace: logging
  labels:
    app: "filebeat-test-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "filebeat-test"
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"

    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:logging-elasticsearch-headless:9200}'
---
# Source: filebeat/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-test-filebeat-cluster-role
  labels:
    app: "filebeat-test-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "filebeat-test"
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    - nodes
    - pods
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - apps
    resources:
    - replicasets
    verbs:
    - get
    - list
    - watch
---
# Source: filebeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-test-filebeat-cluster-role-binding
  labels:
    app: "filebeat-test-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "filebeat-test"
roleRef:
  kind: ClusterRole
  name: filebeat-test-filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: filebeat-test-filebeat
  namespace: logging
---
# Source: filebeat/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filebeat-test-filebeat-role
  namespace: logging
  labels:
    app: "filebeat-test-filebeat"
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
# Source: filebeat/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebeat-test-filebeat-role-binding
  namespace: logging
  labels:
    app: "filebeat-test-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "filebeat-test"
roleRef:
  kind: Role
  name: filebeat-test-filebeat-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: filebeat-test-filebeat
  namespace: logging
---
# Source: filebeat/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-test-filebeat
  namespace: logging
  labels:
    app: "filebeat-test-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "filebeat-test"
spec:
  selector:
    matchLabels:
      app: "filebeat-test-filebeat"
      release: "filebeat-test"
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        configChecksum: ae51a376d2e4eaeab7b0f775cb7a31989078858b3a05886395614fc60f8ed26
      name: "filebeat-test-filebeat"
      labels:
        app: "filebeat-test-filebeat"
        chart: "filebeat-7.17.3"
        heritage: "Helm"
        release: "filebeat-test"
    spec:
      tolerations: []
      nodeSelector: {}
      affinity: {}
      serviceAccountName: filebeat-test-filebeat
      terminationGracePeriodSeconds: 30
      volumes:
      - name: filebeat-config
        configMap:
          defaultMode: 0600
          name: filebeat-test-filebeat-daemonset-config
      - name: data
        hostPath:
          path: /var/lib/filebeat-test-filebeat-logging-data
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: varrundockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: "filebeat"
        image: "registry.cn-guangzhou.aliyuncs.com/kansctl/filebeat:v7.17.3"
        imagePullPolicy: "IfNotPresent"
        args:
        - "-e"
        - "-E"
        - "http.enabled=true"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              filebeat test output
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom: []
        securityContext:
          privileged: false
          runAsUser: 0
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varrundockersock
          mountPath: /var/run/docker.sock
          readOnly: true

