---
kind: Service
apiVersion: v1
metadata:
  name: logging-elasticsearch-headless
  namespace: logging
  labels:
    chart: "logging-elasticsearch"
    app: "logging-elasticsearch"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None 
  publishNotReadyAddresses: true
  selector:
    app: "logging-elasticsearch"
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300

---
apiVersion: v1
kind: Service
metadata:
  name: logging-elasticsearch-outside
  namespace: logging
  labels:
    release: "logging-es"
    chart: "logging-elasticsearch"
    app: "logging-elasticsearch"
  annotations: {}
spec:
  type: NodePort
  selector:
    chart: "logging-elasticsearch"
    app: "logging-elasticsearch"
  publishNotReadyAddresses: false
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30920  
---
kind: Service
apiVersion: v1
metadata:
  name: logging-elasticsearch
  namespace: logging
  labels:
    release: "logging-es"
    chart: "logging-elasticsearch"
    app: "logging-elasticsearch"
  annotations:
    {}
spec:
  type: ClusterIP
  selector:
    chart: "logging-elasticsearch"
    app: "logging-elasticsearch"
  publishNotReadyAddresses: false
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300
  - name : metrics
    port: 9114
