---
- name: 在目录主机创建yaml目录 
  file:
    path: /etc/kansctl/yaml/postgresql-single
    state: directory

- name: 渲染postgresql-single YAML 模板
  template:
    src: "{{ item }}.j2"
    dest: "/etc/kansctl/yaml/postgresql-single/{{ item }}"
    mode: "0660"
  loop:
    - 01-pv-postgresql.yml
    - 02-pvc-postgresql.yml
    - 03-sc-postgresql.yml
    - 04-sts-postgresql.yml
    - 05-svc-postgresql.yml

- name: 部署postgresql-single实例
  shell: kubectl apply -f /etc/kansctl/yaml/postgresql-single 

