---
- name: Creates yaml/postgresql directory
  file:
    path: /etc/kansctl/yaml/postgresql-single
    state: directory

- name: Copying over Redis files for services
  template:
    src: "{{ item }}.j2"
    dest: "/etc/kansctl/yaml/postgresql-single/{{ item }}"
    mode: "0660"
  loop:
    - 01-pv-postgresql.yml
    - 02-pvc-postgresql.yml
    - 03-sc-postgresql.yml
    - 04-sts-postgresql.yml
    - 05-svc-postgresql.yml

- name: Deploy single node postgresql
  shell: kubectl apply -f /etc/kansctl/yaml/postgresql-single 

