---
- name: 在目标主机创建 /etc/kansctl/yaml/prometheus 目录
  file:
    path: /etc/kansctl/yaml/prometheus
    state: directory

- name: 渲染 prometheus 所需要的资源 YAML 清单
  template:
    src: "{{ item }}"
    dest: "/etc/kansctl/yaml/prometheus/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: "0660"
  loop:
    - 01-pv-prometheus.yml.j2
    - 02-pvc-prometheus.yml.j2
    - 03-rbac-monitoring.yml.j2
    - 04-config-prometheus.yml.j2
    - 05-rule-prometheus.yml.j2
    - 06-deploy-prometheus.yml.j2
    - 07-svc-prometheus.yml.j2
    - 08-ingress-prometheus.yml.j2

- name: 部署 prometheus 实例
  shell: kubectl apply -f /etc/kansctl/yaml/prometheus
