---
- name: 在目标主机创建 /etc/kansctl/yaml/elasticsearch 目录 
  file:
    path: /etc/kansctl/yaml/elasticsearch
    state: directory

- name: 渲染 elasticsearch 所需要的资源 YAML 清单 
  template:
    src: "{{ item }}"
    dest: "/etc/kansctl/yaml/elasticsearch/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: "0660"
  loop:
    - 01-sc-elasticsearch.yml.j2
    - 02-pv-elasticsearch.yml.j2
    - 03-sts-elasticsearch.yml.j2
    - 04-svc-elasticsearch.yml.j2    

- name: 部署 elasticsearch 实例
  shell: kubectl apply -f /etc/kansctl/yaml/elasticsearch
