---
- name: 在目录主机创建yaml目录
  file:
    path: /etc/kansctl/yaml/redis-single
    state: directory

- name: 渲染redis-single YAML 模板
  template:
    src: "{{ item }}.j2"
    dest: "/etc/kansctl/yaml/redis-single/{{ item }}"
    mode: "0660"
  loop:
    - 01-pv-redis.yml
    - 02-pvc-redis.yml
    - 03-cm-redis.yml
    - 04-sts-redis.yml
    - 05-svc-redis.yml

- name: 部署redis-single实例
  shell: kubectl apply -f /etc/kansctl/yaml/redis-single 
