- name: apply redis-single
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: redis-single, tags: redis-single, when: service.redis_single is defined }

- name: apply postgresql-single
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: postgresql-single, tags: postgresql-single, when: service.postgresql_single is defined }
