---


## 监控告警
- name: apply prometheus
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: prometheus, tags: prometheus, when: service.prometheus is defined }

- name: apply grafana
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: grafana, tags: grafana, when: service.grafana is defined }

- name: apply alertmanager
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: alertmanager, tags: alertmanager, when: service.alertmanager is defined }

- name: apply node-exporter
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: node-exporter, tags: node-exporter, when: service.node_exporter is defined }

## 数据库
- name: apply redis
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: redis, tags: redis, when: service.redis is defined }

- name: apply postgresql
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: postgresql, tags: postgresql, when: service.postgresql is defined }

- name: apply mysql
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: mysql, tags: mysql, when: service.mysql is defined }

- name: apply elasticsearch
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: elasticsearch, tags: elasticsearch, when: service.elasticsearch is defined }



## 消息队列

- name: apply rabbitmq
  gather_facts: false
  hosts: "{{ k8s_host }}"
  roles:
    - { role: rabbitmq, tags: rabbitmq, when: service.rabbitmq is defined }


#- name: apply prometheus-config-reloader 
#  gather_facts: false
#  hosts: "{{ k8s_host }}"
#  roles:
#    - { role: prometheus-config-reloader, tags: prometheus-config-reloader, when: service.prometheus_config_reloader is defined }
#
#- name: apply prometheus-webhook-dingtalk
#  gather_facts: false
#  hosts: "{{ k8s_host }}"
#  roles:
#    - { role: prometheus-webhook-dingtalk, tags: prometheus-webhook-dingtalk, when: service.prometheus_webhook_dingtalk is defined }
#
